### ISSUE TITLE
Implement authentication for DVID segment layers

### ISSUE THREAD

**Issue by SridharJagannathan** [SridharJagannathan/pyroglancer#3]
Sometimes, the image segmentation layer needs authentication for e.g:

`dvid://https://emdata5-private.janelia.org/blabla/segmentation`

without authentication this leads to an error like:
```
Traceback (most recent call last):
  File "/Users/sri/Documents/Python/neuroglancer/python/neuroglancer/sockjs_handler.py", line 52, in _on_changed
    provider = self.credentials_manager.get(parsed_key['key'], parsed_key.get('parameters'))
  File "/Users/sri/Documents/Python/neuroglancer/python/neuroglancer/credentials_provider.py", line 31, in get
    return self._providers[key](parameters)
KeyError: 'DVID'

```

**Comment by SridharJagannathan** [comment]
Adding reference here to the implementation to be done on the `neuroglancer` side: https://github.com/google/neuroglancer/issues/297

**Comment by SridharJagannathan** [comment]
Refer to PR here: https://github.com/google/neuroglancer/pull/299

**Comment by SridharJagannathan** [comment]
Closed as the PR: https://github.com/google/neuroglancer/pull/299 is merged
